config/routes.rb
AjaxWithRails::Application.routes.draw do
  get "home/index"

  root 'home#index'

  post 'home/submit' => 'home#submit'

end

app/models/word.rb
class Word < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @words = Word.all
  end
  def submit
    new_data = params[:x][:value] 
    word = Word.new()
    word.item = new_data
    word.save
    render json: word.to_json
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
- # Create a form , make sure to have remote true and assign an id for ajax...

.emptySpace

= form_for :x, url: home_submit_path , remote: true , html: {id: "add_item" } do |f|
  .col-lg-3
    = f.label :enter_value , :class => "label label-default", :style => "font-size :20px;"
    %div{:style => "width:20px;height:20px;"}
    .input-group
      = f.text_field :value, :class => "form-control" 
      %span.input-group-btn
        = f.submit :submit, :class => "btn btn-danger"


:coffee
  # Assign ajax events to your form, ensure that div id's match form, and where your json data will be later rendered
  $(document).ready ->
    $("#add_item").on("ajax:success", (e, data, status, xhr) ->
       $("#my_table").prepend("<li class='list-group-item' >" + data.item + " created at " + data.created_at + "</li>")
    ).bind "ajax:error", (e, xhr, status, error) ->
      $("#errors").append(xhr.responseText)

#errors

.emptySpace

- # This div is where your data will be sent after ajax call
%div{:style => "display:block;margin-top:100px;"}
  %h2{:style => "margin-left:15px;"} 
    Saved in database :
  .col-lg-8
    %ul.list-group#my_table
      - @words.each do |w|
        %li.list-group-item 
          = w.item + ". This text was created at " + w.created_at.to_s


:sass
  .emptySpace
    width : 20px
    height : 20px

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AjaxWithRails</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>